name: Semantic Release

on:
  push:
    branches:
      - dev

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Python Semantic Release
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv venv
        uv sync
        ./.venv/bin/semantic-release version