name: Release

on:
  push:
    branches:
      - main
      - dev

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Python Semantic Release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv venv
        uv sync
        ./.venv/bin/semantic-release version
